apiVersion: v2
name: paperless
version: 0.0.0
dependencies:
  - name: paperless
    version: 8.4.0
    repository: https://k8s-at-home.com/charts/
  - name: sftp
    version: 5.1.5
    repository: https://emberstack.github.io/helm-charts
