longhorn:
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  persistence:
    # If you have three or more nodes for storage, use 3; otherwise use 2
    defaultClassReplicaCount: 1  # TODO run DR test to see if we actually need 3
    guaranteedEngineManagerCPU: 15
    guaranteedReplicaManagerCPU: 15
    replicaSoftAntiAffinity: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - &host longhorn.jupiter.mein.nl
  tls:
    - secretName: longhorn-general-tls
      hosts:
        - *host