dexK8sAuthenticator:
  enabled: true
  project: infra-dex-k8s-authenticator
  values:
    global:
      deployEnv: prod
    dexK8sAuthenticator:
      debug: false
      web_path_prefix: /
      #logoUrl: http://<path-to-your-logo.png>
      #tlsCert: /path/to/dex-client.crt
      #tlsKey: /path/to/dex-client.key
      clusters:
      - name: jupiter-cluster
        short_description: "Jupiter Cluster"
        description: "Jupiter Mein Cluster"
        client_secret: "client_Secret"
        issuer: https://dex.jupiter.mein.nl
        k8s_master_uri: https://k8s.jupiter.mein.nl
        client_id: my-cluster
        redirect_uri: https://login.jupiter.mein.nl/callback/my-cluster
        k8s_ca_uri: https://url-to-your-ca.crt
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
      hosts: &host login.jupiter.mein.nl
      # ingress.tls -- Ingress TLS options
      tls:
        - secretName: customer-center-tls
          hosts:
            - *host
dex:
  enabled: true
  project: infra-dex
  values:
    ingress:
      enabled: true
      hosts:
        - &dex dex.jupiter.mein.nl
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
      tls:
        - secretName: customer-center-tls
          hosts:
            - *dex
    grpc: false
    config:
      connectors:
        - type: oidc
          id: authentik
          name: Jupiter
          config:
            # Canonical URL of the provider, also used for configuration discovery.
            # This value MUST match the value returned in the provider config discovery.
            #
            # See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
            issuer: https://authentik.jupiter.mein.nl/application/o/dex/

            # Connector config values starting with a "$" will read from the environment.
            clientID: d27f287e32bb0126c2a18871d0fa1705c31b0bee
            clientSecret: 1c2fd1b956809eb285530483869baf4a470076ce4915dfa05e731a8f9f49bbae8471b6fe219abdf863d3adfb7c804096124918c6300c22d048b199556813f94d

            # Dex's issuer URL + "/callback"
            redirectURI: http://dex.jupiter.mein.nl/callback
      issuer: 'https://dex.jupiter.mein.nl'
      staticClients:
        - id: "oidc-auth-client"
          redirectURIs:
          - 'https://login.jupiter.mein.nl/callback'
          name: 'oidc-auth-client'
          secret: 'Secret'
      enablePasswordDB: false
      oauth2:
        alwaysShowLoginScreen: false