vault:
  injector:
    enabled: false
  server:
    dataStorage:
      storageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host vault.jupiter.mein.nl
      tls:
        - secretName: vault-tls-certificate
          hosts:
            - *host
    dev:
      enabled: false 
