privatebin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host privatebin.jupiter.mein.nl
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: privatebin-tls-certificate
          hosts:
            - *host