- name: Ensure MetalLB namespace exist
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ metallb_namespace }}"
    state: present

- name: Create MetalLB crds for network info
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'crds.yaml.j2') | from_yaml }}"
