apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-laravel-app
  name: sample-laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-laravel-app
  template:
    metadata:
      labels:
        app: sample-laravel-app
    spec:
      containers:
        - name: sample-laravel-app
          image: ealen/echo-server:latest
          imagePullPolicy: Always