  postgresql:
    image:
      repository: bitnami/postgresql
      tag: 14.1.0
    auth:
      existingSecret: postgresql-secret
    persistence:
      enabled: true
      storageClass: longhorn
      size: 4Gi