apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upgrade.yaml

commonAnnotations:
  # TODO https://github.com/rancher/system-upgrade-controller/issues/172
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
