apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-postgresql-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: gitea.postgresql
        property: password
