- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true
- path: gitea/renovate
  data:
    - key: id
      length: 20
      special: false
    - key: token
      length: 40
      special: false
- path: trow/admin
  data:
    - key: password
      length: 32
      special: true
- path: matrix/bot/alert
  data:
    - key: password
      length: 32
      special: true
