authentik:
  authentik:
    secret_key: dontjudgemethisisjustfortesting    # TODO
    postgresql:
      host: postgresql.postgresql.svc.cluster.local
      username: authentik
      password: secret    # TODO
    redis:
      host: redis-master.redis.svc.cluster.local

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host authentik.jupiter.mein.nl
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: authentik-tls-certificate
        hosts:
          - *host

#TODO move to shared postgres
  postgresql:
    enabled: false
    postgresqlPassword: test
    persistence:
      enabled: true
      storageClass: longhorn
  redis:
    enabled: false
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi
