- name: Send Wake-on-LAN magic packets
  community.general.wakeonlan:
    mac: "{{ hostvars[inventory_hostname]['mac'] }}"
  delegate_to: localhost

- name: Wait for the machines to come online
  wait_for_connection:
    timeout: 600
